-- billing_invoices_candidate.sql
-- Candidates for billing generated by ETL

CREATE TABLE IF NOT EXISTS billing_invoices_candidate (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date date NOT NULL,
  customer_id text NOT NULL,
  billable_amount_usd numeric(12,6) NOT NULL,
  cost_usd numeric(12,6) NOT NULL,
  details jsonb,
  status text DEFAULT 'pending', -- pending|invoiced|review
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_candidate_customer_date ON billing_invoices_candidate(customer_id, date);
